export const MOBILE_VERIFICATION = 'MOBILE_VERIFICATION';
export const MOBILE_VERIFICATION_SUCCESS = 'MOBILE_VERIFICATION_SUCCESS';
export const MOBILE_VERIFICATION_FAILURE = 'MOBILE_VERIFICATION_FAILURE';

export const CODE_VERIFICATION = 'CODE_VERIFICATION';
export const CODE_VERIFICATION_SUCCESS = 'CODE_VERIFICATION_SUCCESS';
export const CODE_VERIFICATION_FAILURE = 'CODE_VERIFICATION_FAILURE';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const USER_DATA = 'USER_DATA';

// export const ADD_TO_CART = 'ADD_TO_CART';
// export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

// export const RESET_PIN = 'RESET_PIN';
// export const RESET_PIN_SUCCESS = 'RESET_PIN_SUCCESS';
// export const RESET_PIN_FAILURE = 'RESET_PIN_FAILURE';

// export const GENERATE_OTP = 'GENERATE_OTP';
// export const GENERATE_OTP_SUCCESS = 'GENERATE_OTP_SUCCESS';
// export const GENERATE_OTP_FAILURE = 'GENERATE_OTP_FAILURE';

// export const LOGOUT = 'LOGOUT';
// export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
// export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// export const UPDATE_HEADER_TOKEN = 'UPDATE_HEADER_TOKEN';

// export const SET_GLOBAL_LOADER = 'SET_GLOBAL_LOADER';
